### ISSUE TITLE
Image message in group not recognized as group message sometimes

### ISSUE THREAD

**Issue by quaqo** [adeekshith/watomatic#181] opened 2021-03-09 16:03 UTC
As I found in this [reddit](https://www.reddit.com/r/watomatic/comments/m17ju3/the_app_stop_working/) thread, I also experience the same issue.

Since today the app stopped working.

May I suggest a switch to enable a local logcat that we can share as users?
I also encountered another bug (which I'll report when I can reproduce, basically: if the group switch is off, but someone sends a picture to a group as the first message, this gets autoreplied).

If you need more info, please ask. I'm on 1.10, I'll try as soon as I can with 1.11 on my other device with LineageOS (where I can access more data).

**Comment by adeekshith** [comment] 2021-03-09 16:13
> Since today the app stopped working

Thanks for reporting @quaqo . This looks serious if it happened to more than one person. Will work look into it asap.

> enable a local logcat that we can share as users

Already working on it

> if the group switch is off, but someone sends a picture to a group as the first message, this gets autoreplied.

Oh, will try to reproduce that.

> If you need more info, please ask

Thanks a lot! Will get back to you 😊

**Comment by quaqo** [comment] 2021-03-09 16:16
Thanks to you for being so proactive. Unfortunately I haven't got much time on my hand right now, I wish I could be of more help with a patch.

**Comment by adeekshith** [comment] 2021-03-10 14:27
> I wish I could be of more help with a patch

Really appreciate it! 😊

I found the issue. Updating it now. Hopefully, Google play deploys it fast enough before any serious damage is done.

**Comment by quaqo** [comment] 2021-03-10 14:47
I saw the commit. Good eye, but I don't think it was my issue. I didn't upgrade from the old schema. And I also tried a fresh install.

I enabled a json collector for the notifications so I can give you examples of when it doesn't work, I'll let it run for 24 hrs and report back!

**Comment by adeekshith** [comment] 2021-03-10 23:33
> I think that sometimes a group notification from WhatsApp comes without the group tag at first and then gets updated. This seems to happen consistently for me with picture messages in groups

Thats a very good insight. This probably explains it. As of now it just checks if the notification object has `isGroup` field in the notification object which is either set by WhatsApp or by the OS. Will see if there is any other way. One hacky way is to parse the notification title. Title for groups are in this format: "<groupName>: <person name>". We can detect semi colon or something but there are a thousand ways this can go wrong. Will investigate this.

> I'll build a modified apk when I'll have time

Thanks a lot! @spuday90 is also working on implementing local debug logs. He already did some work in #175 for some ad-hoc testing which is not useful for us yet. But he is working on logging all the events. Will ping you when there is an update there.

Thank you 😊

**Comment by quaqo** [comment] 2021-03-11 12:37
> Thats a very good insight. This probably explains it. As of now it just checks if the notification object has `isGroup` field in the notification object which is either set by WhatsApp or by the OS. Will see if there is any other way. One hacky way is to parse the notification title. Title for groups are in this format: ": ". We can detect semi colon or something but there are a thousand ways this can go wrong. Will investigate this.

FYI, if you want to parse it (I think it would be wise, even though as you said it may go wrong...), from my notification logs, the same message with picture (which seems that is the only type that sometimes doesn't get assigned a isGroup immediately) can appear as:

1. **`isGroup = false`**
`style = Notification.MessagingStyle`
`tickerText = null`
`title = "$GroupName: $ContactName"`
`text = "📷 $PictureCaptionMessage"`
`textSummary = null`

2. **`isGroup = true`**
`style = null`
**`tickerText = "Message from $ContactName @ $GroupName"`** * Localised string
`title = "$GroupName"`
`text = "$ContactName: 📷 $PictureCaptionMessage"`
`textSummary = null`

3. **`isGroup = false`**
**`style = Notification.BigPictureStyle`**
`tickerText = null`
`title = "$ContactName @ $GroupName"`
`text = "📷 $PictureCaptionMessage"`
`textSummary = "$ContactName: 📷 $PictureCaptionMessage"`

As you see, depending of what you parse (ticker, title, text, summary and isgroup) you have different formats:

- group: true / false
- ticker: empty / "Message from Person @ Group"
- title: "Group: Person" / "Person @ Group"
- text: "📷 TEXT" / "Person: 📷 TEXT"
- summary: empty / "Person: 📷 TEXT"

Let me know if this makes sense.


Also thanks to @spuday90 for local debug logs.

**Comment by spuday90** [comment] 2021-03-11 13:13
Hi @quaqo, thanks for the detailed description. Its making a lot sense. We will check more conditions to decide it's a group reply or individual.

**Comment by adeekshith** [comment] 2021-03-11 13:21
@quaqo those logs are very useful! Thanks a lot for that. Yeah, just title many not be of much use but agree we can parse rest of those to decide if it is a group or not.

Also, this happened to me today for personal chat too. My reply frequency was set to 1 day but it replied the second time within a few minutes when the message is an image. Will work on fixing this ASAP.

**Comment by quaqo** [comment] 2021-04-12 12:00
Hi there. Any updates on this? I partially re-created the logic of Watomatic in Tasker, and found that I can safely consider every notification coming from "com.whatsapp" with a ":" in either title or text as a group message.

**Comment by adeekshith** [comment] 2021-04-13 13:22
Hi 👋😊
Yeah I think we have to go with pattern matching. Was searching for a standard solution but could not find anything. Checking for `:` or `text: 📷` (need to verify) might be the only option. Will do this and aim for a release tomorrow. All other group related issues are fixed in previous release but could not do this yet.
Thanks @quaqo

**Comment by adeekshith** [comment] 2021-04-15 13:37
@quaqo Can you help me test this PR please: https://github.com/adeekshith/watomatic/pull/219 

I think it is safe but cannot reproduce the issue on my end.

**Comment by quaqo** [comment] 2021-04-15 13:49
I'm currently AFK and can't compile anything, I do have my second phone thou: are you able to provide me with an APK that I can install?

**Comment by adeekshith** [comment] 2021-04-15 14:04
Awesome! Thanks a lot! 😃
But not urgent. Try whenever you are free.

Github is not allowing me to attach the apk here. Sharing it here: https://transfer.sh/SH8zC/watomatic-issue181-release.apk 
Might want to remove existing app from your system before installing it.

Also attaching the patch image if you want to preview;
<img width="924" alt="181-code-patch" src="https://user-images.githubusercontent.com/2568945/114882344-79a86b00-9dc9-11eb-8b49-7362b0831a0b.png">

**Comment by quaqo** [comment] 2021-04-15 14:06
Already saw the commit, thanks. I'll sideload it ASAP and test it. Thanks!

**Comment by quaqo** [comment] 2021-04-20 07:15
@adeekshith sorry for getting back so late: I had work-related unforeseen issues. I saw you committed the patch, anyways I wanted to chime in anyways and confirm it seems to work on my end! Thank you for fixing it!

**Comment by adeekshith** [comment] 2021-04-20 13:29
@quaqo Oh no probs at all. Thanks a lot for helping to debug and confirming. Planning to release this today and should be available on Play store in 3 to 4 days 😃

**Comment by quaqo** [comment] 2021-04-30 08:16
@adeekshith unfortunately in the last 2 days it happened again.

So this has to be reopen.

What happens is that like I mentioned [here](https://github.com/adeekshith/watomatic/issues/181#issuecomment-796706306):

> * title: "Group: Person" / "Person @ Group"

sometimes the title is "Person @ Group".

Your patch looks if `rawTitle` is of the first kind.

Of the group messages that were answered, both where pictures, but the title was "Person @ Group".

So I think the check should be changed in something like:

`boolean isPossiblyAnImageGrpMsg = ((rawTitle.contains(": ") || rawTitle.contains(" @ ")) && rawText.startsWith("\uD83D\uDCF7"));`

**Comment by spuday90** [comment] 2021-04-30 08:30
Hi @quaqo, 
Sorry to hear that. Just give us some more time we will fix it once and for all. 
Thanks for your detailed observations, that would definitely help us fix the issue faster.

**Comment by quaqo** [comment] 2021-04-30 08:44
> Hi @quaqo,
> Sorry to hear that. Just give us some more time we will fix it once and for all.
> Thanks for your detailed observations, that would definitely help us fix the issue faster.

Thanks to you!

**Comment by quaqo** [comment] 2021-06-04 07:27
Hi there. Any update on this?

**Comment by adeekshith** [comment] 2021-06-05 02:16
Hi @quaqo Will get to it this week.
There was an issue where Watomatic was not working on many devices (battery optimization was killing the app) which was a higher priority so had to work on that. That took a very long time as it is device specific and there is no standard way to fix it. Releasing that update in a day and this is next. Will try to release this by next friday.

This is not happening on any of the device that I have access to so that caused the delay too.
Plan is, will add your fix (below) and in the troubleshooting section, will have a "Run extra checks to prevent accidental group replies" checkbox which can be enabled. So, users will not be confused why auto reply is not working if contact name contains some symbols.

`boolean isPossiblyAnImageGrpMsg = ((rawTitle.contains(": ") || rawTitle.contains(" @ ")) && rawText.startsWith("\uD83D\uDCF7"));`

**Closed** 2021-07-20 04:53 UTC
Labels: bug
