### ISSUE TITLE
Auto-Reply Doesn't work when 2 same messages are received

### ISSUE THREAD

**Issue by pixincreate** [adeekshith/watomatic#106] opened 2021-02-22 15:06 UTC
Yes, Auto-Reply doesn't work when you receive more than 1 message at a time. And if the messages are same, then it doesn't reply either.

### Steps to re-produce:  
-  Send a text(_something like this - "blahh"_) twice on WhatsApp to the one device that you've **Watomatic** installed.
- You can now see that, only message will be sent not 2. When the frequency is un-restricted.

**Comment by adeekshith** [comment] 2021-02-22 15:34
Hi @pixincreate Thanks for reporting this in detail.
As for the not replying for more than one messages issue, this is caused by this line:
https://github.com/adeekshith/watomatic/blob/c98470ef7f57871289e8ab164f6ab09c557c1db6/app/src/main/java/com/parishod/watomatic/NotificationService.java#L29

Where you can see `20*1000 ms` or 20 second relax time between replies. This is causing it. This was introduced to prevent infinite loop if both users contacting each other have Watomatic enabled.

May be 20 seconds is too much. Reducing it to 10 seconds might make it unnoticeable for general users.

I can fix this in a minute but would like to ask if you would like to gain some contribution points 😃.
This is what you should do find line 29 in this file `/app/src/main/java/com/parishod/watomatic/NotificationService.java` and change `20 * 1000` to `10 * 1000`.

Would you like to do that as your first contribution? Let me know.

**Comment by pixincreate** [comment] 2021-02-22 16:27
Just created a pull request for that:)

**Comment by adeekshith** [comment] 2021-02-22 16:51
Great job! 😃
Tiny change is required which I commented in the PR.

https://github.com/adeekshith/watomatic/pull/107#discussion_r580406297

**Comment by adeekshith** [comment] 2021-02-22 23:49
Yayy! Congrats! 🎉 Your first contribution made it to the main repo.
Will move the discussion you posted to another issue and close this one.

**Comment by adeekshith** [comment] 2021-02-22 23:59
You should be able to see your contibutions here: [contributors](https://github.com/adeekshith/watomatic/graphs/contributors).
Looking forward for future contributions! Feel free to raise more issues or PRs in the future and also feel free to ask for help 😊

Moved your discussion here: #111

**Comment by adeekshith** [comment] 2021-02-27 07:31
Attributed your fix in release notes:

- https://www.reddit.com/r/watomatic/comments/ls12ts/watomatic_18_released_with_many_bug_fixes_and_ui/ 
- https://github.com/adeekshith/watomatic/releases/tag/v1.8

Feel free to follow the page (⭐️ it or follow it) for more contributing opportunities. 😃

**Closed** 2021-02-27 08:05 UTC
Labels: bug, good first issue
