### ISSUE TITLE
Doesn't automatically reply when a person send image instead of text

### ISSUE THREAD

**Issue by pixincreate** [adeekshith/watomatic#217] opened 2021-04-13 04:07 UTC
Everything's explained in the title.    
     
**How to reproduce:**  
- Ask a person to send an image
- Watomatic doesn't reply.    
    

Oh! Its actually referenced here before: #181

**Comment by quaqo** [comment] 2021-04-13 08:37
> Oh! Its actually referenced here before: #181

Yes, I think it's a duplicate of what I reported in #181

I'll maybe have sometime next weekend to try to write and submit a patch to @adeekshith (I hope!) as I can't use watomatic at all without that being fixed. My use case is that I have a few groups (actually 2) that I can't move to Signal, but I don't want to spam them with automatic replies. The first picture of the day always gets answered by watomatic and that's not acceptable in this context unfortunately. I still want the occasional person to get the automatic reply when messaging me 1-on-1 thou...

**Comment by adeekshith** [comment] 2021-04-15 13:39
#181 is awaiting review but I doubt this is the same issue. #181 is about replying to image messages when it is not supposed to. I cannot reproduce this on my end. Will take a look.

@pixincreate is the "Reply Frequency" non zero when this happened?

**Comment by pixincreate** [comment] 2021-04-17 10:15
I've kept reply frequency to infinity(•).

**Comment by mawoka-myblock** [comment] 2022-04-15 09:41
@adeekshith Still a thing?

**Comment by adeekshith** [comment] 2022-04-15 12:16
Fixed a while ago

**Closed** 2022-04-15 12:16 UTC
